import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * The tmux-ide app icon. Two artworks — the blue-gradient tile for light
 * surfaces, the black tile for dark ones — swapped by the theme class rather
 * than by JS, so there's no flash on first paint.
 *
 * Referenced by PATH, not by static import: `next-env.d.ts` (which declares the
 * *.png module types) is gitignored and only regenerated by `next build`, so a
 * static import typechecks locally and fails in CI, where lint runs first.
 */
export function AppIcon({
  size = 32,
  className,
  priority = false,
}: {
  size?: number;
  className?: string;
  priority?: boolean;
}) {
  return (
    <span
      className={cn("relative inline-block shrink-0", className)}
      style={{ width: size, height: size }}
    >
      <Image
        src="/icon-light.png"
        alt=""
        width={size}
        height={size}
        priority={priority}
        className="block dark:hidden"
      />
      <Image
        src="/icon-dark.png"
        alt=""
        width={size}
        height={size}
        priority={priority}
        className="hidden dark:block"
      />
    </span>
  );
}
