/** Private, finite IPC vocabulary. Never export a generic renderer channel. */
export const HOST_IPC = {
  bootstrap: "tmux-ide:host/bootstrap",
  lifecycleQuit: "tmux-ide:host/lifecycle/quit",
  windowGetState: "tmux-ide:host/window/get-state",
  windowMinimize: "tmux-ide:host/window/minimize",
  windowToggleMaximized: "tmux-ide:host/window/toggle-maximized",
  windowClose: "tmux-ide:host/window/close",
  windowStateChanged: "tmux-ide:host/window/state-changed",
  menuShowApplication: "tmux-ide:host/menu/show-application",
  workspaceOpenProjectDirectory: "tmux-ide:host/workspace/open-project-directory",
  themeGetState: "tmux-ide:host/theme/get-state",
  themeChanged: "tmux-ide:host/theme/changed",
  daemonRefreshConnection: "tmux-ide:host/daemon/refresh-connection",
  daemonCapabilities: "tmux-ide:host/daemon/capabilities",
  daemonCreateWorkspacePane: "tmux-ide:host/daemon/create-workspace-pane",
  daemonMutateAppWindow: "tmux-ide:host/daemon/mutate-app-window",
  daemonIssueTerminalAttachment: "tmux-ide:host/daemon/issue-terminal-attachment",
  daemonListWorkspaces: "tmux-ide:host/daemon/list-workspaces",
  daemonFetchApplicationShell: "tmux-ide:host/daemon/fetch-application-shell",
  daemonSubscribe: "tmux-ide:host/daemon/subscribe",
  daemonUnsubscribe: "tmux-ide:host/daemon/unsubscribe",
  daemonEvent: "tmux-ide:host/daemon/event",
} as const;

export const HOST_INVOKE_CHANNELS = [
  HOST_IPC.bootstrap,
  HOST_IPC.lifecycleQuit,
  HOST_IPC.windowGetState,
  HOST_IPC.windowMinimize,
  HOST_IPC.windowToggleMaximized,
  HOST_IPC.windowClose,
  HOST_IPC.menuShowApplication,
  HOST_IPC.workspaceOpenProjectDirectory,
  HOST_IPC.themeGetState,
  HOST_IPC.daemonRefreshConnection,
  HOST_IPC.daemonCapabilities,
  HOST_IPC.daemonCreateWorkspacePane,
  HOST_IPC.daemonMutateAppWindow,
  HOST_IPC.daemonIssueTerminalAttachment,
  HOST_IPC.daemonListWorkspaces,
  HOST_IPC.daemonFetchApplicationShell,
  HOST_IPC.daemonSubscribe,
  HOST_IPC.daemonUnsubscribe,
] as const;
