// Derive a fresh closed lane; never edit preparation receipt or original host.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,realpathSync} from 'node:fs';import {createHash} from 'node:crypto';
const read=p=>JSON.parse(readFileSync(p)),sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const spec=read('/evidence/base-spec.json'),component=read('/inputs/component-receipt.json');assert.equal(component.noFixturesStarted,true);assert.equal(component.sourceBase,spec.host.candidate.base);assert.equal(component.cliSha256,spec.cliSha256);assert.deepEqual(component.explicitComponentWindows,[0,16,32]);
const closure={...spec.closure,...component.closure};for(const [p,h] of Object.entries(closure))assert.equal(sha(p),h,p);
for(const p of ['/evidence/component-host.json','/inputs/component-receipt.json','/inputs/run-tail.py','/inputs/freeze-tail.mjs','/inputs/verify-components.mjs','/inputs/lane-verify.mjs','/inputs/tail_gate.py','/inputs/gate-tail.py','/inputs/bounded.py','/inputs/admit_topology.py','/inputs/cpu_environment.py','/inputs/closure.py','/inputs/extract_runtime.py','/work/source/.tasks/components-linux/tail/verify.mjs','/work/source/.tasks/components-linux/tail/reference.json'])closure[realpathSync(p)]=sha(p);
assert.deepEqual(read('/evidence/component-host.json'),spec.host);
const sourceManifest='/work/source/.tasks/components-linux/tail/source-at-prepare.json';writeFileSync(sourceManifest,JSON.stringify({hashes:closure},null,2),{flag:'wx',mode:0o600});closure[sourceManifest]=sha(sourceManifest);
const frozen={...spec,lane:'tail3',output:'/evidence/tail-results',closure,resolutions:[...spec.resolutions,...component.extraResolutions],componentSharedClosures:component.sharedClosures,componentOverlaySha256:'0718450c6823dfb590f88f8e313338c7f016cc73303ef57bfdc0346a3ac7061e',scope:'cb6/private32 base; explicit component0/16/32 tail3'};
writeFileSync('/evidence/frozen-tail.json',JSON.stringify(frozen,null,2),{flag:'wx',mode:0o600});console.log(JSON.stringify({specSha256:sha('/evidence/frozen-tail.json'),closureFiles:Object.keys(closure).length,componentHostSha256:sha('/evidence/component-host.json')}));
