import { defineConfig, type Plugin } from "vite";
import solid from "vite-plugin-solid";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, renameSync, readdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));

/**
 * Content-hash the bundle and hand the app its URL.
 *
 * The island is loaded by a <script src> from public/, which browsers cache by
 * filename — a fixed name means a deploy ships new code that returning visitors
 * never fetch (this bit us in dev: a stale bundle rendered the OLD sidebar and
 * looked like a routing bug). Hashing the name makes the URL change whenever the
 * bytes do, and the generated constant keeps the <script> tag honest.
 */
function hashedAsset(): Plugin {
  return {
    name: "tui-hashed-asset",
    closeBundle() {
      const outDir = here("../public");
      const built = join(outDir, "tui-demo.js");
      const hash = createHash("sha256").update(readFileSync(built)).digest("hex").slice(0, 8);
      // Drop stale hashes — emptyOutDir is off (public/ holds other assets).
      for (const f of readdirSync(outDir)) {
        if (/^tui-demo\.[a-f0-9]{8}\.js$/.test(f)) unlinkSync(join(outDir, f));
      }
      const name = `tui-demo.${hash}.js`;
      renameSync(built, join(outDir, name));
      writeFileSync(
        here("../lib/tui-asset.ts"),
        `// GENERATED by tui-web/vite.config.ts — do not edit.\nexport const TUI_DEMO_SRC = "/${name}";\n`,
      );
    },
  };
}

/**
 * Builds the TUI island as a standalone IIFE into public/, kept OUT of the Next
 * build for two reasons:
 *
 *  1. Solid's JSX needs babel-preset-solid; Next compiles with SWC and has no
 *     Solid plugin. A separate Vite pass sidesteps that entirely.
 *  2. `generate: "universal"` is what redirects JSX at our web host (host.ts)
 *     instead of at solid-js/web's DOM renderer — that flag is the whole trick.
 */
export default defineConfig({
  plugins: [
    hashedAsset(),
    solid({
      solid: {
        generate: "universal",
        moduleName: here("./host.ts"),
      },
    }),
  ],
  resolve: {
    alias: [
      // The app's shared pure modules import RGBA from core, which is native-only.
      { find: "@opentui/core", replacement: here("./opentui-shim.ts") },
      // Import the daemon's real logic straight from source.
      { find: /^@daemon\/(.*)$/, replacement: here("../../packages/daemon/src/$1") },
    ],
  },
  build: {
    lib: {
      entry: here("./main.tsx"),
      name: "TuiDemo",
      formats: ["iife"],
      fileName: () => "tui-demo.js",
    },
    outDir: here("../public"),
    emptyOutDir: false,
    target: "es2020",
  },
});
