import * as stylex from "@stylexjs/stylex";
export const s = stylex.create({
  app: {
    backgroundColor: "var(--chrome)",
    backgroundImage: "var(--frame-gradient)",
    color: "var(--text)",
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    minHeight: 280,
  },
  backgroundTabs: {
    backgroundColor: { ":hover": "var(--tint)", default: "transparent" },
    borderRadius: "var(--radius-panel)",
    borderWidth: 0,
    color: { ":hover": "var(--text)", default: "var(--muted)" },
    cursor: "pointer",
    flexShrink: 0,
    fontSize: { "@media (max-width: 600px)": 13, default: 14 },
    fontVariantNumeric: "tabular-nums",
    fontWeight: 500,
    height: 36,
    paddingInline: { "@media (max-width: 600px)": 8, default: 12 },
    whiteSpace: "nowrap",
  },
  badge: {
    backgroundColor: "var(--tint)",
    borderRadius: 6,
    color: "var(--muted)",
    fontSize: 12,
    padding: "2px 5px",
    whiteSpace: "nowrap",
  },
  branch: { minHeight: 0, minWidth: 0 },
  canvas: {
    flex: 1,
    marginBottom: { "@media (max-width: 600px)": 4, default: 6 },
    marginInline: { "@media (max-width: 600px)": 4, default: 6 },
    minHeight: 0,
    position: "relative",
  },
  checkSlot: { display: "inline-flex", flexShrink: 0, height: 14, width: 14 },
  confirmation: {
    alignItems: "center",
    display: "flex",
    flexBasis: "100%",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "flex-end",
  },
  connectionDot: {
    backgroundColor: "#e8b96f",
    borderRadius: "50%",
    bottom: 5,
    height: 6,
    insetInlineEnd: 6,
    position: "absolute",
    width: 6,
  },
  danger: { color: "var(--danger)" },
  empty: {
    color: "var(--muted)",
    fontSize: 12,
    lineHeight: 1.8,
    padding: "34px 12px",
    textAlign: "center",
  },
  exit: {
    backdropFilter: "blur(24px)",
    backgroundColor: "var(--overlay-fill)",
    borderRadius: 12,
    bottom: 16,
    boxShadow: "var(--tab-shadow)",
    left: "50%",
    maxWidth: "calc(100% - 24px)",
    position: "absolute",
    transform: "translateX(-50%)",
    width: "max-content",
    zIndex: 5,
  },
  fieldError: { color: "var(--danger)", fontSize: 13, lineHeight: 1.5 },
  fieldLabel: {
    color: "var(--muted)",
    display: "block",
    fontSize: 13,
    marginTop: 18,
  },
  focusedPane: {
    backgroundColor: "var(--panel-active-fill)",
  },
  glyph: {
    alignItems: "center",
    backgroundImage: "var(--tab-surface)",
    borderRadius: 8,
    boxShadow: "var(--tab-shadow)",
    color: "var(--accent)",
    display: "flex",
    flexShrink: 0,
    height: 30,
    justifyContent: "center",
    width: 32,
  },
  handle: {
    alignItems: "center",
    backgroundColor: {
      ":active": "#ffffff0e",
      ":hover": "#ffffff08",
      default: "transparent",
    },
    borderRadius: 5,
    cursor: "col-resize",
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    position: "relative",
    touchAction: "none",
    width: 6,
  },
  handleLine: {
    backgroundColor: "transparent",
    borderRadius: 2,
    height: 24,
    width: 2,
  },
  handleLineVertical: { height: 2, width: 24 },
  handleVertical: { cursor: "row-resize", height: 6, width: "100%" },
  heading: {
    fontSize: 27,
    fontWeight: 500,
    letterSpacing: "-1px",
    lineHeight: 1.15,
    margin: 0,
    textWrap: "balance",
  },
  hidden: { display: "none" },
  iconButton: {
    alignItems: "center",
    backgroundColor: { ":hover": "var(--tint)", default: "transparent" },
    borderRadius: 8,
    borderWidth: 0,
    color: { ":hover": "var(--text)", default: "var(--control-ink)" },
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    height: 36,
    justifyContent: "center",
    padding: 0,
    transition: "color 120ms, background-color 120ms",
    width: 36,
  },
  inlineNotice: {
    alignItems: "center",
    backgroundColor: "var(--panel-fill)",
    borderRadius: 12,
    boxShadow: "var(--panel-shadow)",
    color: "var(--text)",
    display: "flex",
    fontSize: 13,
    gap: 10,
    lineHeight: 1.5,
    marginTop: 16,
    overflowWrap: "anywhere",
    padding: 12,
  },
  input: {
    backgroundColor: "var(--panel-fill)",
    borderRadius: 9,
    borderWidth: 0,
    boxShadow: "var(--panel-shadow)",
    color: "var(--text)",
    fontSize: { "@media (max-width: 600px)": 16, default: 14 },
    marginTop: 8,
    padding: "11px 12px",
    width: "100%",
  },
  key: {
    backgroundColor: "var(--tint)",
    borderColor: "var(--border)",
    borderRadius: 5,
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    fontFamily: "var(--font-ui)",
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
    padding: "2px 5px",
    whiteSpace: "nowrap",
  },
  mobileHide: { "@media (max-width: 600px)": { display: "none" } },
  modal: {
    backdropFilter: "blur(32px) saturate(1.3)",
    backgroundColor: "var(--overlay-fill)",
    backgroundImage: "var(--glass-sheen)",
    borderRadius: 24,
    borderWidth: 0,
    boxShadow: "var(--panel-shadow), var(--overlay-shadow)",
    maxHeight: "min(760px, calc(100dvh - 32px))",
    maxWidth: "100%",
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: { "@media (max-width: 600px)": 20, default: 24 },
    width: 470,
  },
  modalHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 550,
    letterSpacing: "-.5px",
    margin: 0,
  },
  modalWide: { width: 540 },
  numeric: { fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" },
  overlay: {
    alignItems: "center",
    backdropFilter: "blur(5px)",
    backgroundColor: "var(--scrim)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    padding: 16,
    position: "fixed",
    zIndex: 30,
  },
  paletteDisabled: { cursor: "default", opacity: 0.45 },
  paletteEmpty: {
    alignItems: "center",
    color: "var(--muted)",
    display: "flex",
    flexDirection: "column",
    fontSize: 14,
    gap: 8,
    justifyContent: "center",
    minHeight: 108,
    overflowWrap: "anywhere",
    padding: "28px 20px",
    textAlign: "center",
  },
  paletteEscape: {
    backgroundColor: { ":hover": "var(--tint)", default: "var(--panel-fill)" },
    borderRadius: 7,
    borderWidth: 0,
    boxShadow: "var(--panel-shadow)",
    color: "var(--muted)",
    cursor: "pointer",
    flexShrink: 0,
    fontSize: 11,
    height: 28,
    minWidth: 32,
    padding: "0 6px",
  },
  paletteFooter: {
    alignItems: "center",
    backgroundColor: "var(--panel-fill)",
    color: "var(--muted)",
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    fontSize: 11,
    gap: "10px 16px",
    justifyContent: "space-between",
    padding: "12px 16px",
  },
  paletteGroup: { padding: "8px 8px 4px" },
  paletteGroupHeading: {
    color: "var(--muted)",
    display: "block",
    fontSize: 12,
    fontWeight: 500,
    padding: "8px 12px",
    userSelect: "none",
  },
  paletteHelp: {
    alignItems: "center",
    display: "flex",
    gap: 12,
    whiteSpace: "nowrap",
  },
  paletteHint: {
    alignItems: "center",
    color: "var(--muted)",
    display: { "@media (max-width: 400px)": "none", default: "flex" },
    flexShrink: 0,
    fontSize: 11,
    gap: 3,
  },
  paletteInput: {
    "::placeholder": { color: "var(--muted)" },
    ":focus-visible": {
      boxShadow: "0 2px 0 var(--control-ink)",
      outlineStyle: {
        "@media (forced-colors: active)": "auto",
        default: "none",
      },
    },
    backgroundColor: "transparent",
    borderRadius: 6,
    borderWidth: 0,
    caretColor: "var(--accent)",
    color: "var(--text)",
    fontFamily: "inherit",
    fontSize: { "@media (max-width: 600px)": 16, default: 18 },
    minWidth: 0,
    padding: "10px 2px",
    width: "100%",
  },
  paletteItem: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "var(--radius-panel)",
    color: "var(--text)",
    cursor: "pointer",
    display: "flex",
    fontSize: 14,
    gap: 12,
    marginBottom: 4,
    minHeight: 48,
    padding: "10px 12px",
    position: "relative",
    userSelect: "none",
  },
  paletteItemIcon: {
    color: "var(--control-ink)",
    display: "flex",
    flexShrink: 0,
  },
  paletteItemLabel: {
    flex: 1,
    lineHeight: 1.45,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  paletteKey: {
    alignItems: "center",
    backgroundColor: "var(--panel-fill)",
    borderRadius: 4,
    boxShadow: "var(--panel-shadow)",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 500,
    height: 20,
    justifyContent: "center",
    minWidth: 18,
    paddingInline: 3,
  },
  paletteList: {
    maxHeight: "min(360px, calc(100dvh - 180px))",
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarColor: "var(--control-ink) transparent",
    scrollbarWidth: "thin",
    scrollPaddingBlock: 8,
  },
  paletteModal: {
    borderRadius: 18,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    padding: 0,
    width: 640,
  },
  paletteMore: { fontSize: 11, whiteSpace: "nowrap" },
  paletteNotice: { flexShrink: 0, margin: "12px 12px 0" },
  paletteReturn: {
    color: "var(--muted)",
    flexShrink: 0,
    fontSize: 16,
    width: 14,
  },
  paletteRoot: { display: "flex", flexDirection: "column", minHeight: 0 },
  paletteSearch: {
    alignItems: "center",
    boxShadow: "0 1px 0 var(--tint)",
    display: "flex",
    flexShrink: 0,
    gap: 12,
    minHeight: 68,
    padding: "10px 16px",
  },
  paletteSearchIcon: {
    color: "var(--control-ink)",
    display: "flex",
    flexShrink: 0,
  },
  paletteSelected: {
    backgroundColor: "var(--panel-fill)",
    backgroundImage: "var(--tab-surface)",
    boxShadow: "var(--tab-shadow)",
  },
  paletteSelectedHint: { color: "var(--text)" },
  paletteStatus: {
    flex: "1 1 190px",
    lineHeight: 1.5,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  pane: {
    backdropFilter: "blur(28px) saturate(1.15)",
    backgroundColor: "var(--panel-fill)",
    backgroundImage: "var(--glass-sheen)",
    borderRadius: "var(--radius-panel)",
    borderWidth: 0,
    boxShadow: "var(--panel-shadow)",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
    transition: "background-color 120ms",
  },
  paneAction: { borderRadius: 4, height: 24, width: 24 },
  paneHeader: {
    alignItems: "center",
    color: "var(--text)",
    display: "flex",
    flexShrink: 0,
    gap: 6,
    height: "var(--height-pane-header)",
    paddingInline: 8,
  },
  paneHeading: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    height: "100%",
    minWidth: 0,
  },
  paneHide: { borderRadius: 4, height: 24, width: 24 },
  paneHideSlot: { alignItems: "center", display: "flex", flexShrink: 0 },
  paneIcon: { flexShrink: 0 },
  paneLabel: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  paneName: {
    flex: 1,
    fontSize: { "@media (max-width: 600px)": 12, default: 12 },
    fontWeight: 500,
    letterSpacing: "-.25px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  paragraph: {
    color: "var(--muted)",
    fontSize: 13,
    lineHeight: 1.6,
    margin: 0,
    maxWidth: 320,
    textWrap: "pretty",
  },
  primary: {
    alignItems: "center",
    backdropFilter: "blur(24px)",
    backgroundColor: {
      ":hover": "var(--panel-active-fill)",
      default: "var(--tint)",
    },
    backgroundImage: "var(--tab-surface)",
    borderRadius: 12,
    borderWidth: 0,
    boxShadow: "var(--tab-shadow)",
    color: "var(--text)",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 13,
    fontWeight: 550,
    gap: 8,
    justifyContent: "center",
    minHeight: 40,
    padding: "10px 16px",
  },
  row: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
    paddingBlock: 13,
  },
  scrollCue: {
    backdropFilter: "blur(16px)",
    backgroundColor: "var(--overlay-fill)",
    borderRadius: 9,
    bottom: 0,
    boxShadow: "var(--tab-shadow)",
    color: "var(--text)",
    fontSize: 12,
    insetInlineEnd: 0,
    padding: "5px 9px",
    position: "absolute",
  },
  scrollCuePosition: {
    bottom: -8,
    height: 0,
    pointerEvents: "none",
    position: "sticky",
  },
  search: {
    alignItems: "center",
    backdropFilter: "blur(24px)",
    backgroundColor: "var(--overlay-fill)",
    backgroundImage: "var(--tab-surface)",
    borderRadius: 14,
    borderWidth: 0,
    boxShadow: "var(--tab-shadow)",
    display: "flex",
    gap: 3,
    insetInlineEnd: 9,
    padding: 5,
    position: "absolute",
    top: 48,
    width: "min(320px, 90%)",
    zIndex: 10,
  },
  searchInput: {
    backgroundColor: "transparent",
    borderRadius: 9,
    borderWidth: 0,
    color: "var(--text)",
    flex: 1,
    fontSize: { "@media (max-width: 600px)": 16, default: 14 },
    minWidth: 0,
    padding: "6px 7px",
  },
  sectionTitle: {
    color: "var(--muted)",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0",
    marginBottom: 12,
    marginTop: 23,
  },
  segment: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 12,
    borderWidth: 0,
    color: "var(--muted)",
    cursor: "pointer",
    display: "flex",
    flex: 1,
    fontSize: 12,
    gap: 7,
    justifyContent: "center",
    minHeight: 40,
    padding: "8px 5px",
  },
  segmentActive: {
    backdropFilter: "blur(24px)",
    backgroundColor: "var(--panel-fill)",
    backgroundImage: "var(--tab-surface)",
    boxShadow: "var(--tab-shadow)",
    color: "var(--text)",
  },
  segmented: {
    backgroundColor: "var(--tint)",
    borderRadius: 16,
    display: "flex",
    gap: 4,
    marginTop: 18,
    padding: 4,
  },
  sessionName: { fontSize: 14, lineHeight: 1.5, overflowWrap: "anywhere" },
  sessionRow: {
    alignItems: "center",
    backgroundColor: "var(--panel-fill)",
    borderRadius: 16,
    boxShadow: "var(--panel-shadow)",
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
    padding: 12,
  },
  skip: {
    backgroundColor: "var(--overlay-fill)",
    borderRadius: 12,
    borderWidth: 0,
    color: "var(--text)",
    insetInlineStart: 8,
    padding: 12,
    position: "fixed",
    top: 8,
    transform: {
      ":focus-visible": "translateY(0)",
      default: "translateY(-200%)",
    },
    zIndex: 70,
  },
  srOnly: {
    clipPath: "inset(50%)",
    height: 1,
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: 1,
  },
  subtle: {
    color: "var(--muted)",
    fontSize: 12,
    lineHeight: 1.6,
    overflowWrap: "anywhere",
  },
  swatch: {
    borderRadius: 12,
    boxShadow: "var(--panel-shadow)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    height: 70,
    padding: "9px 8px",
  },
  swatchDot: { borderRadius: "50%", height: 4, opacity: 0.6, width: 4 },
  swatchLine: { borderRadius: 2, height: 3, opacity: 0.5 },
  swatchTop: { display: "flex", gap: 3, marginBottom: 4 },
  tab: {
    alignItems: "center",
    backgroundColor: { ":hover": "var(--tint)", default: "transparent" },
    borderRadius: 16,
    borderWidth: 0,
    color: "var(--muted)",
    cursor: "pointer",
    display: "flex",
    flex: "1 0 136px",
    gap: 6,
    height: { "@media (max-width: 600px)": 34, default: "var(--height-row)" },
    maxWidth: 260,
    minWidth: { "@media (max-width: 600px)": 130, default: 136 },
    paddingInline: 10,
    position: "relative",
    touchAction: "pan-x",
    transition: "background-color 120ms, color 120ms",
    userSelect: "none",
  },
  tabActive: {
    backdropFilter: "blur(24px) saturate(1.35)",
    backgroundColor: "var(--panel-fill)",
    backgroundImage: "var(--tab-surface)",
    borderColor: "transparent",
    boxShadow: "var(--tab-shadow)",
    color: "var(--text)",
  },
  tabCanvas: { inset: 0, minHeight: 0, minWidth: 0, position: "absolute" },
  tabStrip: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    gap: 6,
    marginInline: -8,
    minWidth: 0,
    overflowX: "auto",
    paddingBlock: { "@media (max-width: 600px)": 6, default: 6 },
    paddingInline: 8,
    scrollbarWidth: "none",
  },
  tabs: {
    alignItems: "center",
    display: "flex",
    flex: "1 0 0",
    gap: 10,
    maxWidth: "max-content",
    minWidth: "min-content",
  },
  tabText: {
    flex: 1,
    fontSize: { "@media (max-width: 600px)": 13, default: 13 },
    fontWeight: 500,
    letterSpacing: "-.35px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tabTrigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 12,
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    flex: 1,
    gap: 6,
    height: "100%",
    minWidth: 0,
    padding: 0,
    textAlign: "start",
  },
  terminal: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    padding: "3px 7px 6px 8px",
    position: "relative",
  },
  textButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: { ":hover": "var(--text)", default: "var(--muted)" },
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 13,
    gap: 6,
    padding: "4px 2px",
  },
  themeCard: {
    backgroundColor: { ":hover": "var(--tint)", default: "transparent" },
    borderRadius: 16,
    borderWidth: 0,
    color: "var(--text)",
    cursor: "pointer",
    minWidth: 0,
    padding: 4,
    textAlign: "start",
  },
  themeGrid: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      "@media (max-width: 360px)": "repeat(2, minmax(0, 1fr))",
      default: "repeat(3, minmax(0, 1fr))",
    },
  },
  themeLabel: {
    alignItems: "center",
    display: "flex",
    fontSize: 12,
    gap: 2,
    justifyContent: "space-between",
    padding: "8px 4px 6px",
  },
  themeSelected: {
    backgroundColor: "var(--panel-fill)",
    backgroundImage: "var(--tab-surface)",
    boxShadow: "var(--tab-shadow)",
  },
  tinyButton: { height: 30, width: 28 },
  toast: {
    alignItems: "center",
    backdropFilter: "blur(24px)",
    backgroundColor: "var(--overlay-fill)",
    backgroundImage: "var(--tab-surface)",
    borderRadius: "var(--radius-panel)",
    borderWidth: 0,
    boxShadow: "var(--tab-shadow)",
    color: "var(--text)",
    display: "flex",
    fontSize: 12,
    gap: 12,
    overflowWrap: "anywhere",
    padding: "12px 18px",
    pointerEvents: "auto",
    width: "min(520px, calc(100vw - 32px))",
  },
  toastPosition: {
    bottom: 24,
    display: "flex",
    insetInline: 16,
    justifyContent: "center",
    pointerEvents: "none",
    position: "fixed",
    zIndex: 60,
  },
  toolbar: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: { "@media (max-width: 600px)": 6, default: 8 },
    height: { "@media (max-width: 600px)": 44, default: "var(--height-toolbar)" },
    paddingInline: { "@media (max-width: 600px)": 6, default: 8 },
  },
  tree: {
    display: "flex",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    width: "100%",
  },
  vertical: { flexDirection: "column" },
  welcome: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    justifyContent: "center",
    minHeight: "100%",
    padding: 24,
    textAlign: "center",
  },
  welcomeIcon: {
    alignItems: "center",
    backdropFilter: "blur(24px)",
    backgroundColor: "var(--panel-fill)",
    backgroundImage: "var(--tab-surface)",
    borderRadius: 20,
    borderWidth: 0,
    boxShadow: "var(--tab-shadow)",
    color: "var(--accent)",
    display: "flex",
    height: 65,
    justifyContent: "center",
    marginBottom: 6,
    transform: "rotate(-6deg)",
    width: 65,
  },
  welcomeScroll: {
    inset: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    position: "absolute",
  },
  workspace: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
    paddingBottom: "env(safe-area-inset-bottom)",
    paddingTop: "env(safe-area-inset-top)",
  },
  workspaceMenu: { marginInlineEnd: 4, position: "relative" },
});
