export {
  startEmbeddedDaemon,
  type EmbeddedDaemonHandle,
  type EmbeddedDaemonOptions,
} from "./embed.ts";
export {
  canonicalDaemonUrl,
  clearCanonicalDaemonInfoIfOwned,
  clearCanonicalDaemonInfoIfUnchanged,
  getCanonicalDaemonClaimPath,
  inspectCanonicalDaemonInfo,
  isCanonicalDaemonAlive,
  isCanonicalDaemonRecordOwnerProvenDead,
  probeCanonicalDaemonHealth,
  probeCanonicalDaemonIdentity,
  readCanonicalDaemonInfo,
  releaseCanonicalDaemonClaim,
  tryAcquireCanonicalDaemonClaim,
  writeCanonicalDaemonInfo,
} from "./canonical.ts";
export type {
  CanonicalDaemonInfo,
  CanonicalDaemonInfoInvalidReason,
  CanonicalDaemonInfoObservation,
  CanonicalDaemonInfoState,
  CanonicalDaemonClaim,
  CanonicalDaemonClaimAttempt,
} from "./canonical.ts";
export {
  MissionRepository,
  MissionRepositoryError,
  applyMissionEvent,
  replayMissionEvents,
  type MissionAttempt,
  type MissionHistoryEntry,
  type MissionProjectState,
  type MissionRepositorySnapshot,
  type MissionSnapshot,
  type MissionTask,
} from "./lib/mission-repository.ts";
export {
  MissionProjectionError,
  missionStatusToBoardColumn,
  projectMissionBoard,
  projectMissionDetail,
  projectMissionHistory,
  projectMissionTimeline,
  taskStatusToBoardColumn,
  type MissionProjectionErrorCode,
  type MissionProjectionOptions,
} from "./lib/mission-projections.ts";
export {
  APP_WINDOW_DOCUMENT_PATH,
  AppWindowRepositoryError,
  AppWindowService,
  type AppWindowRepositoryDiagnostic,
  type AppWindowRepositoryErrorCode,
  type AppWindowServiceMigrationOptions,
  type AppWindowServiceOptions,
  type AppWindowWriterLockOptions,
  type ExecuteAppWindowCommandOptions,
  type LoadedAppWindowDocument,
  type ResetAppWindowDocumentRequest,
  type ResetAppWindowDocumentResult,
} from "./lib/app-window-repository.ts";
export {
  APP_WINDOW_FLOAT_MIN_HEIGHT,
  APP_WINDOW_FLOAT_MIN_WIDTH,
  AppWindowKernelError,
  type AppWindowCommand,
  type AppWindowKernelErrorCode,
} from "./lib/app-window-kernel.ts";
export {
  CorruptRuntimeDocumentError,
  MissingRuntimeDocumentError,
  ProjectRuntimeRepository,
  ProjectRuntimeRepositoryError,
  ProjectRuntimeWriterLockTimeoutError,
  RevisionConflictError,
  createProjectRuntimeRepository,
  openProjectRuntimeRepository,
  type OpenProjectRuntimeRepositoryOptions,
  type ProjectRuntimeDocument,
  type ProjectRuntimeMetadata,
  type ProjectRuntimeRepositoryOptions,
  type ProjectRuntimeWriterLockOptions,
  type RecoverDocumentOptions,
  type RecoverDocumentResult,
  type WriteDocumentOptions,
  type WriteDocumentResult,
} from "./lib/project-runtime-repository.ts";
export {
  classifyProjectReadiness,
  type AuthenticationReadiness,
  type Availability,
  type CommandReadiness,
  type ConfigFreeLaunchPane,
  type ConfigFreeLaunchPlan,
  type HarnessKind,
  type HarnessReadinessState,
  type ProjectHarnessReadiness,
  type ProjectReadinessGitProbe,
  type ProjectReadinessHarnessProbe,
  type ProjectReadinessIssue,
  type ProjectReadinessIssueCode,
  type ProjectReadinessIssueSeverity,
  type ProjectReadinessPlatformProbe,
  type ProjectPathKind,
  type ProjectReadinessProbe,
  type ProjectReadinessProjectProbe,
  type ProjectReadinessResult,
  type ProjectReadinessToolProbe,
  type ProjectRecoveryAction,
  type ProjectRecoveryActionKind,
  type ProjectRegistrationState,
} from "./lib/project-readiness.ts";
export {
  assessProjectReadiness,
  probeProjectReadiness,
  type CustomReadinessHarnessProfile,
  type ProjectReadinessProbeIo,
  type ProjectReadinessProbeOptions,
  type ReadinessCommandOptions,
  type ReadinessCommandResult,
  type ReadinessCommandStatus,
  type ReadinessExecutableKind,
  type ReadinessPathKind,
} from "./lib/project-readiness-probe.ts";
export {
  SemanticPaneCatalog,
  SemanticPaneCatalogError,
  TrustedSemanticPaneSnapshotSchemaZ,
  semanticPaneTargetKey,
  type SemanticPaneCatalogErrorCode,
  type SemanticPaneCatalogOptions,
  type SemanticPaneResolution,
  type SemanticPaneRuntimeProof,
  type TrustedSemanticPaneSnapshot,
} from "./terminal/attachments/semantic-pane-catalog.ts";
export {
  AttachmentLeaseError,
  AttachmentLeaseManager,
  type AttachmentCleanupStatus,
  type AttachmentIssueContext,
  type AttachmentLeaseAuditEvent,
  type AttachmentLeaseBinding,
  type AttachmentLeaseDescriptor,
  type AttachmentLeaseErrorCode,
  type AttachmentLeaseManagerOptions,
  type AttachmentLeaseStatus,
  type AttachmentOrphanReconciliationResult,
  type AttachmentViewOperation,
  type AttachmentViewExecutor,
  type EnumeratedMarkedAttachmentView,
  type ExecutedAttachmentViewOperation,
  type GuardedAttachmentViewOperation,
  type GuardedAttachmentViewOperationResult,
  type GuardedAttachmentCleanup,
  type GuardedAttachmentCleanupResult,
  type IssuedAttachmentLease,
  type RedeemedAttachmentLease,
  type ReconciledOrphanAttachmentDescriptor,
} from "./terminal/attachments/lease-manager.ts";
export {
  TmuxAttachmentViewExecutor,
  TmuxAttachmentViewExecutorError,
  type TmuxAttachmentCommandResult,
  type TmuxAttachmentCommandRunner,
  type TmuxAttachmentViewExecutorErrorCode,
  type TmuxAttachmentViewExecutorOptions,
} from "./terminal/attachments/tmux-view-executor.ts";
